version: '3'
services:
  redis-server:
    image: 'redis'

  mothership:
    build:
      context: ./authSatServer
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9001"
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./authSatServer:/app
    restart: unless-stopped