version: '3'
services:
  redis-server:
    image: 'redis'

  auth-sat-server:
    build:
      context: ./authSatServer
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9001"
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./authSatServer:/app
    restart: unless-stopped

  http-server:
    build:
      context: ./httpServer
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - /app/node_modules
      - ./httpServer:/app
    restart: unless-stopped