version: '3'
services:

  redis-server:
    image: 'redis'
  mongo:
    image: 'mongo:3.6'

  auth-sat-server:
    build:
      context: ./auth-sat-server
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9001"
    volumes:
      - /app/node_modules
      - ./auth-sat-server:/app
    restart: unless-stopped

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
      - "5555:5555"
    volumes:
      - /app/node_modules
      - ./api-server:/app
    restart: unless-stopped
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - URL
      - WS_PORT
      - WS_URL

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on: 
      - frontend
      - auth-sat-server
      - api-server
      - redis-server
      - mongo
    restart: unless-stopped