version: '3'
services:
  redis-server:
    image: 'redis'

  auth-sat-server:
    build:
      context: ./auth-sat-server
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9001"
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./auth-sat-server:/app
    restart: unless-stopped

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - /app/node_modules
      - ./api-server:/app
    restart: unless-stopped

  auth-frontend:
    build:
      context: ./auth-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./auth-frontend:/app